language: node_js
node_js:
  - "11.10.1"
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - ~/.cache
jobs:
  include:
    - stage: Tests
      name: Run All Tests
      script:
        - yarn test
        - yarn lint
    - stage: Deploy
      name: Deploy to GitHub pages
      if: branch = dev
      branches:
        only:
        - dev
      install:
        - yarn
        - yarn generate
      script:
        - echo "Deploying to GitHub pages ..."
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_ACCESS_TOKEN
        target-branch: master
        local-dir: dist
        on:
          branch: dev