language: node_js
node_js:
  - node
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - ~/.cache
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script: yarn test:unit
    - name: E2E Tests
      script: yarn test:e2e
    - stage: Deploy
      name: Deploy to GitHub pages
      if: branch = dev
      branches:
        only:
        - dev
      install:
        - yarn
        - yarn generate
      script:
        - echo "Deploying to GitHub pages ..."
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_ACCESS_TOKEN
        target-branch: master
        local-dir: dist
        on:
          branch: dev